//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_Server_Creator.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MinecraftServerCreator_Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MinecraftServerCreator_Data() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_Server_Creator.Resources.MinecraftServerCreator_Data", typeof(MinecraftServerCreator_Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version
        ///1.17.1
        ///Size
        ///42.8 MB
        ///Release date
        ///Tuesday, July 06 2021
        ///Download
        ///https://download.getbukkit.org/craftbukkit/craftbukkit-1.17.1.jar
        ///Version
        ///1.17
        ///Size
        ///42.7 MB
        ///Release date
        ///Friday, June 11 2021
        ///Download
        ///https://download.getbukkit.org/craftbukkit/craftbukkit-1.17.jar
        ///Version
        ///1.16.5
        ///Size
        ///33.92 MB
        ///Release date
        ///Sunday, January 17 2021
        ///Download
        ///https://cdn.getbukkit.org/craftbukkit/craftbukkit-1.16.5.jar
        ///Version
        ///1.16.4
        ///Size
        ///33.87 MB
        ///Release date
        ///Thursday, October 29 2020
        ///Download
        ///https://cdn.getbukkit.org/cr [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string bukkit {
            get {
                return ResourceManager.GetString("bukkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon GermanNightmare_logo {
            get {
                object obj = ResourceManager.GetObject("GermanNightmare_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap server_icon {
            get {
                object obj = ResourceManager.GetObject("server_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version
        ///1.17.1
        ///Size
        ///43.1 MB
        ///Release date
        ///Tuesday, July 06 2021
        ///Download
        ///https://download.getbukkit.org/spigot/spigot-1.17.1.jar
        ///Version
        ///1.17
        ///Size
        ///43.0 MB
        ///Release date
        ///Friday, June 11 2021
        ///Download
        ///https://download.getbukkit.org/spigot/spigot-1.17.jar
        ///Version
        ///1.16.5
        ///Size
        ///34.18 MB
        ///Release date
        ///Sunday, January 17 2021
        ///Download
        ///https://cdn.getbukkit.org/spigot/spigot-1.16.5.jar
        ///Version
        ///1.16.4
        ///Size
        ///34.13 MB
        ///Release date
        ///Thursday, October 29 2020
        ///Download
        ///https://cdn.getbukkit.org/spigot/spigot-1.16.4.jar
        ///Version [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string spigot {
            get {
                return ResourceManager.GetString("spigot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version
        ///1.17.1
        ///Size
        ///41.6 MB
        ///Release date
        ///Tuesday, July 06 2021
        ///Download
        ///https://launcher.mojang.com/v1/objects/a16d67e5807f57fc4e550299cf20226194497dc2/server.jar
        ///Version
        ///1.17
        ///Size
        ///41.6 MB
        ///Release date
        ///Tuesday, June 08 2021
        ///Download
        ///https://launcher.mojang.com/v1/objects/0a269b5f2c5b93b1712d0f5dc43b6182b9ab254e/server.jar
        ///Version
        ///1.16.5
        ///Size
        ///36.2 MB
        ///Release date
        ///Friday, January 15 2021
        ///Download
        ///https://launcher.mojang.com/v1/objects/35139deedbd5182953cf1caa23835da59ca3d7cd/server.jar
        ///Version
        ///1.16.4
        ///Size
        ///36. [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string vanilla {
            get {
                return ResourceManager.GetString("vanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wood_sign {
            get {
                object obj = ResourceManager.GetObject("wood_sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wood_wall {
            get {
                object obj = ResourceManager.GetObject("wood_wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
